website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from .models import SudskaOdluka, Sud
from . import db
from .servisi import DodajSudServis, DodajSudskuOdlukuServis, AzuriranjeServis
import json
from flask import flash
from .PoslovnaLogika import PoslovnaLogika, LogikaJMBG

config_path = 'website/config.json'
with open('website/config.json', 'r') as file_config:
    config = json.load(file_config)

max_jmbg = config.get("maksimalan_broj_jmbgova") # OVO JE ZA POSLOVNU LOGIKU I IMPORT CONFIGA

azuriranje_servis = AzuriranjeServis()
dodaj_sud_service = DodajSudServis()
dodaj_odluku_service = DodajSudskuOdlukuServis()
ValidacijaJMBG = LogikaJMBG()
#blueprint za izdvajanje pregleda u više fajlova
views = Blueprint('views', __name__)
#definisanje blueprinta



@views.route('/stampa-azuriranje/<int:odlukaID>', methods=['GET', 'POST'])
@login_required
def stampa_azuriranje(odlukaID):

    return redirect(url_for('views.home'))


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        jmbg_filter = request.form.get('jmbg_filter')
        if jmbg_filter:
            # Filtrirajte sudske odluke na osnovu unetog filtera
            sudske_odluke = SudskaOdluka.query.filter(SudskaOdluka.JMBG_list.contains(jmbg_filter)).all()
        else:
            # Ako filter nije unet, prikažite sve sudske odluke
            sudske_odluke = SudskaOdluka.query.all()
    else:
        # Ako nije poslat POST zahtev, prikažite sve sudske odluke
        sudske_odluke = SudskaOdluka.query.all()

    return render_template("glavno.html", user=current_user, sudski_odluke=sudske_odluke)

@views.route('dodajOdluku', methods = ['GET', 'POST'])
@login_required
def dodaj():
    sudovi = Sud.query.all()

    if request.method == 'POST':
        naslov = request.form.get('naslov')
        sadrzaj = request.form.get('sadrzaj')
        jmbg_list_str = request.form.get('jmbg_list')
        sud_ime = request.form.get('sud')
        if ValidacijaJMBG.validacija(jmbg_list_str):

            if dodaj_odluku_service.dodaj(naslov, sadrzaj, jmbg_list_str, sud_ime):
                flash('Нова одлука је додата!', category='success')
            else:
                flash('Суд са изабраним именом није пронађен или није могуће додати одлуку.', category='error')
    return render_template("dodajOdluku.html", user=current_user, sudovi=sudovi)

@views.route('/dodajSud', methods=['GET', 'POST'])
@login_required
def dodaj_sud():
    if request.method == 'POST':
        naziv = request.form.get('naziv')
        mesto = request.form.get('mesto')

        # Koristite servis za dodavanje suda
        if dodaj_sud_service.dodaj(naziv, mesto):
            flash('Суд је успешно додат!', category='success')
            return redirect(url_for('views.home'))  # Redirektuj korisnika na glavnu stranicu nakon dodavanja suda
        else:
            flash('Морате унети све информације.', category='error')

    return render_template("dodajSud.html", user=current_user)

@views.route('/stampa-odluke/<int:odlukaID>', methods=['GET'])
def stampa_odluke(odlukaID):
    odluka = SudskaOdluka.query.get(odlukaID)
    if not odluka:
        flash('Sudska odluka nije pronađena.', category='error')
        return redirect(url_for('views.home'))

    # Dodajte odluku suda u odluku
    sud = Sud.query.get(odluka.sud_id)
    if sud:
        odluka.sud = sud

    return render_template("stampa.html", user=current_user, odluka=odluka)

@views.route('/delete-odluka/<int:odluka_id>', methods=['POST','GET'])
def delete_odluka(odluka_id):
    odluka = SudskaOdluka.query.get(odluka_id)
    db.session.delete(odluka)
    db.session.commit()
    flash('Одлука је успешно обрисана!', category='success')
    return redirect(url_for('views.home'))

@views.route('/azuriranje/<int:odlukaID>', methods=['GET', 'POST'])
@login_required
def azuriranje(odlukaID):
    odluka = SudskaOdluka.query.get(odlukaID)
    sudovi = Sud.query.all()  # Dohvatite sve sudove za padajući izbornik

    if not odluka:
        return redirect(url_for('views.home'))

    if request.method == 'POST':
        naslov = request.form.get('naslov')
        sadrzaj = request.form.get('sadrzaj')
        sud_id = request.form.get('sud_id')
        jmbg_list_str = request.form.get('jmbg_list')
        if len(jmbg_list_str) > 10:
            flash('унели сте превише ЈМБГ-а')
        if azuriranje_servis.dodaj(odluka, naslov, sadrzaj, jmbg_list_str, sud_id):
            flash('Одлука је успешно ажурирана!', category='success')
            return redirect(url_for('views.home'))
        else:
            flash('Морате унети све информације.', category='error')

    return render_template("azuriranje.html", user=current_user, odluka=odluka, sudovi=sudovi)

website/templates/azuriranje.html
{% extends "base.html" %}
{% block title %}Ажурирање одлуке{% endblock %}
{% block content %}
    <h1 align="center">Ажурирање Судске одлуке</h1>
    <form method="POST">
        <input type="hidden" name="odlukaID" value="{{ odluka.OdlukaID }}">
        <!-- Dodajte ostala polja za unos podataka i popunite ih sa vrednostima izabrane odluke -->
        <div class="form-group">
            <label for="naslov">Наслов:</label>
            <input type="text" class="form-control" id="naslov" name="naslov" value="{{ odluka.Naslov }}">
        </div>
        <div class="form-group">
            <label for="sadrzaj">Садржај:</label>
            <textarea class="form-control" id="sadrzaj" name="sadrzaj">{{ odluka.Sadrzaj }}</textarea>
        </div>
        <div class="form-group">
            <label for="sud_id">Суд:</label>
            <select class="form-control" id="sud_id" name="sud_id">
                {% for sud in sudovi %}
                    <option value="{{ sud.id }}"
                            {% if sud.id == odluka.sud_id %}selected{% endif %}>{{ sud.naziv }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="jmbg_list">ЈМБГ Листа (Раздвојите зарезима):</label>
            <input type="text" class="form-control" id="jmbg_list" name="jmbg_list"
                   value="{{ ','.join(odluka.JMBG_list) }}">
        </div>
        <!-- Dodajte ostala polja za unos podataka i popunite ih sa vrednostima izabrane odluke -->
        <div align="center">
            <button type="submit" class="btn btn-primary">Сачувај Ажурирање</button>
        </div>
    </form>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head> <!--head sadrži metadata o sajtu-->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    /> <!--link za CDN ( content delivery network) koji omogućava
    da učitamo bootstrap bez skidanja fajla.
    skidamo css , jer rel = "stylesheet" -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Главно{% endblock %}</title> <!--python se definiše unutar
     { % bloka, koji se . block title znači da će svaki child template naslediti ovaj template.
      children template se može promeniti -->
  </head>
  <body><!--body sadrži html-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar"> <!--navbar bootstrepa za navigaciju-->
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Главна</a>
          <a class="nav-item nav-link" id="logout" href="/logout">одјави се</a>
          {% if user.jeovlascen %}
            <a class="nav-item nav-link" id="dodajSud" href="/dodajSud">Додај суд</a>
            <a class="nav-item nav-link" id="dodajOdluku" href="/dodajOdluku">Додај одлуку</a>
          {% endif %}
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Пријава</a>
          <a class="nav-item nav-link" id="registracija" href="/registracija">Регистрација</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %} <!--Prolazi kroz sve flash poruke, ako postoje -->
    <div class="alert alert-danger alter-dismissable fade show" role="alert"> <!--alert moze da se dissmisuje-->
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <!--javascript za bootstrap animacije.
    u static folder se stavljaju svi fajlovi koji se neće menjati, css, js, koji će se učitati -->
{% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
  fetch("/delete-note", {
    method: "POST",
    body: JSON.stringify({ noteId: noteId }),
  }).then((_res) => {
    window.location.href = "/";
  });
  }
</script>
{% endblock %}
  </body>
</html>

website/templates/dodajLicnuKartu.html
{% extends "base.html" %}

{% block title %}Додавање нове Личне Карте{% endblock %}

{% block content %}
<div class="container">
    <h2 class="mt-4">Додај нову Личну Карту</h2>
    <form method="POST">
        <div class="form-group">
            <label for="broj_licne_karte">Број Личне Карте:</label>
            <input type="text" class="form-control" id="broj_licne_karte" name="broj_licne_karte" required>
        </div>
        <div class="form-group">
            <label for="naziv_sup_izdao">Назив СУП-а који је издао:</label>
            <input type="text" class="form-control" id="naziv_sup_izdao" name="naziv_sup_izdao" required>
        </div>
        <div class="form-group">
            <label for="mesto_sup_izdao">Место СУП-а који је издао:</label>
            <input type="text" class="form-control" id="mesto_sup_izdao" name="mesto_sup_izdao" required>
        </div>
        <div class="form-group">
            <label for="jmbg_vlasnika">ЈМБГ Власника:</label>
            <input type="text" class="form-control" id="jmbg_vlasnika" name="jmbg_vlasnika" required>
        </div>
        <div class="form-group">
            <label for="prezime_vlasnika">Презиме Власника:</label>
            <input type="text" class="form-control" id="prezime_vlasnika" name="prezime_vlasnika" required>
        </div>
        <div class="form-group">
            <label for="ime_vlasnika">Име Власника:</label>
            <input type="text" class="form-control" id="ime_vlasnika" name="ime_vlasnika" required>
        </div>
        <div class="form-group">
            <label for="datum_izdavanja">Датум Издавања:</label>
            <input type="date" class="form-control" id="datum_izdavanja" name="datum_izdavanja" required>
        </div>
        <div class="form-group">
            <label for="broj_godina_vazenja">Број Година Важења:</label>
            <input type="text" class="form-control" id="broj_godina_vazenja" name="broj_godina_vazenja" required>
        </div>

        <button type="submit" class="btn btn-primary">Додај Личну Карту</button>
    </form>
</div>
{% endblock %}

website/templates/dodajOdluku.html
{% extends "base.html" %}

{% block title %}Додавање нове одлуке{% endblock %}

{% block content %}
    <div class="container">
        <h2 class="mt-4">Додај нову судску одлуку</h2>
        <form method="POST" enctype="multipart/form-data">
            <div class="form-group">
                <label for="naslov">Наслов:</label>
                <input type="text" class="form-control" id="naslov" name="naslov" required>
            </div>
            <div class="form-group">
                <label for="sadrzaj">Садржај:</label>
                <textarea class="form-control" id="sadrzaj" name="sadrzaj" rows="5" required></textarea>
            </div>
            <div class="form-group">
                <label for="jmbg_list">ЈМБГ Странки (одвојен зарезом)</label>
                <input type="text" class="form-control" id="jmbg_list" name="jmbg_list"
                       placeholder="Unesite JMBG-ove odvojene zarezima" required>
            </div>
            <div class="form-group">
                <label for="sud">Изаберите суд:</label>
                <select class="form-control" id="sud" name="sud">
                    {% for sud in sudovi %}
                        <option value="{{ sud.naziv }}">{{ sud.naziv }}</option>
                    {% endfor %}
                </select>
            </div>

            <button type="submit" class="btn btn-primary">Додај Одлуку</button>
        </form>
    </div>
{% endblock %}



website/templates/dodajSud.html
{% extends "base.html" %}
{% block title %}Додај Суд{% endblock %}
{% block content %}
<div class="container">
    <h1 align="center">Додај Суд</h1>
    <form method="POST">
        <div class="form-group">
            <label for="naziv">Назив Суда</label>
            <input type="text" class="form-control" id="naziv" name="naziv" placeholder="Унесите назив суда">
        </div>
        <div class="form-group">
            <label for="mesto">Место Суда</label>
            <input type="text" class="form-control" id="mesto" name="mesto" placeholder="Унесите место суда">
        </div>
        <button type="submit" class="btn btn-primary">Додај Суд</button>
    </form>
</div>
{% endblock %}

website/templates/glavno.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%} <!--extenduje base.html, biće identičan kao base.html samo što se može menjati.
Ako umesto home stavio nešto drugo, promeniće ga u base.html-u-->
    <h1 align="center">Судске одлуке</h1>
    <form method="POST">
    <div class="form-group">
        <label for="jmbg_filter">Филтер по JMBG:</label>
        <input type="text" class="form-control" id="jmbg_filter" name="jmbg_filter" placeholder="Унесите JMBG">
    </div>
    <button type="submit" class="btn btn-primary">Примени филтер</button>
</form>
    {% if user.jeovlascen %}
        <table class="table">
    <thead>
      <tr>
        <th scope="col">Наслов</th>
        <th scope="col">Датум</th>
          <th scope="col">Бриши</th>
          <th scope="col">Ажурирај</th>
          <th scope="col">Штампај</th>
      </tr>
    </thead>
    <tbody>
      {% for odluka in sudski_odluke %}
        <tr>
          <td>{{ odluka.Naslov }}</td>
          <td>{{ odluka.date.strftime('%Y-%m-%d %H:%M:%S') }}</td>
             <td>
                <a href="{{ url_for('views.delete_odluka', odluka_id=odluka.OdlukaID) }}" class="btn btn-danger btn-sm">Обриши</a>
            </td>
            <td>
                <a href="{{ url_for('views.azuriranje', odlukaID=odluka.OdlukaID) }}" class="btn btn-secondary">Ажурирање</a>
                <button type="button" class="close" onClick="brisiOdluku({{ odluka.OdlukaID }})">

                </button>
            </td>
            <td>
                <a href="{{ url_for('views.stampa_odluke', odlukaID=odluka.OdlukaID) }}" class="btn btn-info"> Штампај</a>
            </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
        {% else %}
        <table class="table">
    <thead>
      <tr>
        <th scope="col">Наслов</th>
        <th scope="col">Датум</th>
          <th scope="col">Штампај</th>
      </tr>
    </thead>
    <tbody>
      {% for odluka in sudski_odluke %}
        <tr>
          <td>{{ odluka.Naslov }}</td>
          <td>{{ odluka.date.strftime('%Y-%m-%d %H:%M:%S') }}</td>
            <td>
                <a href="{{ url_for('views.stampa_odluke', odlukaID=odluka.OdlukaID) }}" class="btn btn-info"> Штампај</a>
            </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

    {% endif %}


{% endblock %}

website/templates/glavno2.html
{% extends "base.html" %}
{% block title %}Личне Карте{% endblock %}
{% block content %}
    <h1 align="center">Личне Карте</h1>
    <form method="POST">
        <div class="form-group">
            <label for="jmbg_filter">Филтер по JMBG:</label>
            <input type="text" class="form-control" id="jmbg_filter" name="jmbg_filter" placeholder="Унесите JMBG">
        </div>
        <button type="submit" class="btn btn-primary">Примени филтер</button>
    </form>
    {% if user.jeovlascen %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Број Личне Карте</th>
                    <th scope="col">Назив СУП Издао</th>
                    <th scope="col">Место СУП Издао</th>
                    <th scope="col">JMBG Власника</th>
                    <th scope="col">Презиме Власника</th>
                    <th scope="col">Име Власника</th>
                    <th scope="col">Датум Издавања</th>
                    <th scope="col">Број Година Важења</th>
                    <th scope="col">Бриши</th>
                    <th scope="col">Ажурирај</th>
                    <th scope="col">Штампај</th>
                </tr>
            </thead>
            <tbody>
                {% for licna_karta in licne_karte %}
                    <tr>
                        <td>{{ licna_karta.BrojLicneKarte }}</td>
                        <td>{{ licna_karta.NazivSUPIzdao }}</td>
                        <td>{{ licna_karta.MestoSUPIzdao }}</td>
                        <td>{{ licna_karta.JMBGVlasnika }}</td>
                        <td>{{ licna_karta.PrezimeVlasnika }}</td>
                        <td>{{ licna_karta.ImeVlasnika }}</td>
                        <td>{{ licna_karta.DatumIzdavanja }}</td>
                        <td>{{ licna_karta.BrojGodinaVazenja }}</td>
                        <td>
                            <a href="{{ url_for('views.delete_licna_karta', BrojLicneKarte=licna_karta.BrojLicneKarte) }}" class="btn btn-danger btn-sm">Обриши</a>
                        </td>
                        <td>
                            <a href="{{ url_for('views.azuriranje_licna_karta', BrojLicneKarte=licna_karta.BrojLicneKarte) }}" class="btn btn-secondary">Ажурирање</a>
                        </td>
                        <td>
                            <a href="{{ url_for('views.stampaj_licna_karta', BrojLicneKarte=licna_karta.BrojLicneKarte) }}" class="btn btn-info"> Штампај</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Број Личне Карте</th>
                    <th scope="col">Назив СУП Издао</th>
                    <th scope="col">Место СУП Издао</th>
                    <th scope="col">JMBG Власника</th>
                    <th scope="col">Презиме Власника</th>
                    <th scope="col">Име Власника</th>
                    <th scope="col">Датум Издавања</th>
                    <th scope="col">Број Година Важења</th>
                    <th scope="col">Штампај</th>
                </tr>
            </thead>
            <tbody>
                {% for licna_karta in licne_karte %}
                    <tr>
                        <td>{{ licna_karta.BrojLicneKarte }}</td>
                        <td>{{ licna_karta.NazivSUPIzdao }}</td>
                        <td>{{ licna_karta.MestoSUPIzdao }}</td>
                        <td>{{ licna_karta.JMBGVlasnika }}</td>
                        <td>{{ licna_karta.PrezimeVlasnika }}</td>
                        <td>{{ licna_karta.ImeVlasnika }}</td>
                        <td>{{ licna_karta.DatumIzdavanja }}</td>
                        <td>{{ licna_karta.BrojGodinaVazenja }}</td>
                        <td>
                            <a href="{{ url_for('views.stampaj_licna_karta', BrojLicneKarte=licna_karta.BrojLicneKarte) }}" class="btn btn-info"> Штампај</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Пријава{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Пријава</h3>
  <div class="form-group">
    <label for="email">Имејл адреса</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="унесите имејл"
    />
  </div>
  <div class="form-group">
    <label for="sifra">Шифра</label>
    <input
      type="password"
      class="form-control"
      id="sifra"
      name="sifra"
      placeholder="Унесите шифру"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Пријава</button>
</form>
{% endblock %}

website/templates/registracija.html
{% extends "base.html" %} {% block title %}регистрација{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Регистрација</h3>
  <div class="form-group">
    <label for="email">Имејл адреса</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Унесите имејл"
    />
  </div>
  <div class="form-group">
    <label for="ime">Име</label>
    <input
      type="text"
      class="form-control"
      id="ime"
      name="ime"
      placeholder="унесите име"
    />
  </div>

  <div class="form-group">
    <label for="sifra1">Шифра</label>
    <input
      type="password"
      class="form-control"
      id="sifra1"
      name="sifra1"
      placeholder="унесите шифру"
    />
  </div>
  <div class="form-group">
    <label for="sifra2">Шифра (Потврди)</label>
    <input
      type="password"
      class="form-control"
      id="sifra2"
      name="sifra2"
      placeholder="потврдите шифру"
    />
  </div>
    <div class="form-check">
    <input type="checkbox" class="form-check-input" id="jeovlascen" name="jeovlascen">
    <label class="form-check-label" for="jeovlascen">Ovlašćen korisnik</label>
</div>

  <br />

    <br>
  <button type="submit" class="btn btn-primary">Прихвати</button>
</form>
{% endblock %}

website/templates/stampa.html
{% extends "base.html" %} <!-- Extendujemo base.html -->
{% block title %}Штампање Одлуке{% endblock %} <!-- Postavljamo naslov stranice -->
{% block content %}
    <div class="container">
        <h1 align="center">Детаљи судске одлуке</h1>
        <table class="table">
            <tr>
                <th scope="col">Наслов</th>
                <td>{{ odluka.Naslov }}</td> <!-- Prikazujemo naslov odluke -->
            </tr>
            <tr>
                <th scope="col">Датум</th>
                <td>{{ odluka.date.strftime('%Y-%m-%d %H:%M:%S') }}</td> <!-- Prikazujemo datum -->
            </tr>
            <tr>
                <th scope="col">Садржај</th>
                <td>{{ odluka.Sadrzaj }}</td> <!-- Prikazujemo sadržaj odluke -->
            </tr>
            <tr>
                <th scope="col">Суд</th>
                <td>{{ odluka.sud.naziv }}</td> <!-- Prikazujemo naziv suda -->
            </tr>
            <tr>
                <th scope="col">JMBG Листа</th>
                <td>
                    <ol>
                        {% for jmbg in odluka.JMBG_list %}
                            <li>{{ jmbg }}</li> <!-- Prikazujemo listu JMBG brojeva -->
                        {% endfor %}
                    </ol>
                </td>
            </tr>
            <tr>
                <th scope="col"></th>
                <td>
                    <form action="{{ url_for('views.stampa_azuriranje', odlukaID=odluka.OdlukaID) }}" method="POST">
                        <button type="submit" class="btn btn-success">Назад на почетну</button>
                    </form>
                </td>
            </tr>
        </table>

    </div>

{% endblock %}